package com.boat.pension.model;

import java.io.Serializable;

public class Admin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer instid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.cname
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.license
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String license;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.state
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.instID
     *
     * @return the value of admin.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getInstid() {
        return instid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.instID
     *
     * @param instid the value for admin.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setInstid(Integer instid) {
        this.instid = instid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.cname
     *
     * @return the value of admin.cname
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.cname
     *
     * @param cname the value for admin.cname
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.license
     *
     * @return the value of admin.license
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.license
     *
     * @param license the value for admin.license
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setLicense(String license) {
        this.license = license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.state
     *
     * @return the value of admin.state
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.state
     *
     * @param state the value for admin.state
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", instid=").append(instid);
        sb.append(", cname=").append(cname);
        sb.append(", license=").append(license);
        sb.append(", password=").append(password);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}