package com.boat.pension.model;

import java.io.Serializable;

public class Building implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column building.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column building.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer instid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column building.name
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table building
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.id
     *
     * @return the value of building.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.id
     *
     * @param id the value for building.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.instID
     *
     * @return the value of building.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getInstid() {
        return instid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.instID
     *
     * @param instid the value for building.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setInstid(Integer instid) {
        this.instid = instid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column building.name
     *
     * @return the value of building.name
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column building.name
     *
     * @param name the value for building.name
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", instid=").append(instid);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}