package com.boat.pension.model;

import java.io.Serializable;
import java.util.Date;

public class Device implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.deviceID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer deviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer instid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.state
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.registerTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Date registertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.deviceID
     *
     * @return the value of device.deviceID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.deviceID
     *
     * @param deviceid the value for device.deviceID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setDeviceid(Integer deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.instID
     *
     * @return the value of device.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getInstid() {
        return instid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.instID
     *
     * @param instid the value for device.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setInstid(Integer instid) {
        this.instid = instid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.state
     *
     * @return the value of device.state
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.state
     *
     * @param state the value for device.state
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.registerTime
     *
     * @return the value of device.registerTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.registerTime
     *
     * @param registertime the value for device.registerTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deviceid=").append(deviceid);
        sb.append(", instid=").append(instid);
        sb.append(", state=").append(state);
        sb.append(", registertime=").append(registertime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}