package com.boat.pension.model;

import java.io.Serializable;
import java.util.Date;

public class Event implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.seniorID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer seniorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.name
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.deviceID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer deviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer instid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.type
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.startTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.state
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.enterTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Date entertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.endTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.handler
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String handler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.location
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.resultText
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String resulttext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table event
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.id
     *
     * @return the value of event.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.id
     *
     * @param id the value for event.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.seniorID
     *
     * @return the value of event.seniorID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getSeniorid() {
        return seniorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.seniorID
     *
     * @param seniorid the value for event.seniorID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setSeniorid(Integer seniorid) {
        this.seniorid = seniorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.name
     *
     * @return the value of event.name
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.name
     *
     * @param name the value for event.name
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.deviceID
     *
     * @return the value of event.deviceID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.deviceID
     *
     * @param deviceid the value for event.deviceID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setDeviceid(Integer deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.instID
     *
     * @return the value of event.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getInstid() {
        return instid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.instID
     *
     * @param instid the value for event.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setInstid(Integer instid) {
        this.instid = instid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.type
     *
     * @return the value of event.type
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.type
     *
     * @param type the value for event.type
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.startTime
     *
     * @return the value of event.startTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.startTime
     *
     * @param starttime the value for event.startTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.state
     *
     * @return the value of event.state
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.state
     *
     * @param state the value for event.state
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.enterTime
     *
     * @return the value of event.enterTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Date getEntertime() {
        return entertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.enterTime
     *
     * @param entertime the value for event.enterTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setEntertime(Date entertime) {
        this.entertime = entertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.endTime
     *
     * @return the value of event.endTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.endTime
     *
     * @param endtime the value for event.endTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.handler
     *
     * @return the value of event.handler
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getHandler() {
        return handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.handler
     *
     * @param handler the value for event.handler
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setHandler(String handler) {
        this.handler = handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.location
     *
     * @return the value of event.location
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.location
     *
     * @param location the value for event.location
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.resultText
     *
     * @return the value of event.resultText
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getResulttext() {
        return resulttext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.resultText
     *
     * @param resulttext the value for event.resultText
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setResulttext(String resulttext) {
        this.resulttext = resulttext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", seniorid=").append(seniorid);
        sb.append(", name=").append(name);
        sb.append(", deviceid=").append(deviceid);
        sb.append(", instid=").append(instid);
        sb.append(", type=").append(type);
        sb.append(", starttime=").append(starttime);
        sb.append(", state=").append(state);
        sb.append(", entertime=").append(entertime);
        sb.append(", endtime=").append(endtime);
        sb.append(", handler=").append(handler);
        sb.append(", location=").append(location);
        sb.append(", resulttext=").append(resulttext);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}