package com.boat.pension.model;

import java.io.Serializable;
import java.util.Date;

public class Monitorlog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitorlog.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitorlog.seniorID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer seniorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitorlog.deviceID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer deviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitorlog.logDate
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Date logdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitorlog.location
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitorlog.startTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitorlog.endTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitorlog.heartArr
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String heartarr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitorlog.breathArr
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String breatharr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monitorlog
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitorlog.id
     *
     * @return the value of monitorlog.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitorlog.id
     *
     * @param id the value for monitorlog.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitorlog.seniorID
     *
     * @return the value of monitorlog.seniorID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getSeniorid() {
        return seniorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitorlog.seniorID
     *
     * @param seniorid the value for monitorlog.seniorID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setSeniorid(Integer seniorid) {
        this.seniorid = seniorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitorlog.deviceID
     *
     * @return the value of monitorlog.deviceID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitorlog.deviceID
     *
     * @param deviceid the value for monitorlog.deviceID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setDeviceid(Integer deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitorlog.logDate
     *
     * @return the value of monitorlog.logDate
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Date getLogdate() {
        return logdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitorlog.logDate
     *
     * @param logdate the value for monitorlog.logDate
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setLogdate(Date logdate) {
        this.logdate = logdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitorlog.location
     *
     * @return the value of monitorlog.location
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitorlog.location
     *
     * @param location the value for monitorlog.location
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitorlog.startTime
     *
     * @return the value of monitorlog.startTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitorlog.startTime
     *
     * @param starttime the value for monitorlog.startTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitorlog.endTime
     *
     * @return the value of monitorlog.endTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitorlog.endTime
     *
     * @param endtime the value for monitorlog.endTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitorlog.heartArr
     *
     * @return the value of monitorlog.heartArr
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getHeartarr() {
        return heartarr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitorlog.heartArr
     *
     * @param heartarr the value for monitorlog.heartArr
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setHeartarr(String heartarr) {
        this.heartarr = heartarr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitorlog.breathArr
     *
     * @return the value of monitorlog.breathArr
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getBreatharr() {
        return breatharr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitorlog.breathArr
     *
     * @param breatharr the value for monitorlog.breathArr
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setBreatharr(String breatharr) {
        this.breatharr = breatharr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorlog
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", seniorid=").append(seniorid);
        sb.append(", deviceid=").append(deviceid);
        sb.append(", logdate=").append(logdate);
        sb.append(", location=").append(location);
        sb.append(", starttime=").append(starttime);
        sb.append(", endtime=").append(endtime);
        sb.append(", heartarr=").append(heartarr);
        sb.append(", breatharr=").append(breatharr);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}