package com.boat.pension.model;

import java.io.Serializable;
import java.util.Date;

public class Record implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.deviceID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer deviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.realtime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Date realtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.heart
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer heart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.breath
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer breath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table record
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.id
     *
     * @return the value of record.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.id
     *
     * @param id the value for record.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.deviceID
     *
     * @return the value of record.deviceID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.deviceID
     *
     * @param deviceid the value for record.deviceID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setDeviceid(Integer deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.realtime
     *
     * @return the value of record.realtime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Date getRealtime() {
        return realtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.realtime
     *
     * @param realtime the value for record.realtime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setRealtime(Date realtime) {
        this.realtime = realtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.heart
     *
     * @return the value of record.heart
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getHeart() {
        return heart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.heart
     *
     * @param heart the value for record.heart
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setHeart(Integer heart) {
        this.heart = heart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.breath
     *
     * @return the value of record.breath
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getBreath() {
        return breath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.breath
     *
     * @param breath the value for record.breath
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setBreath(Integer breath) {
        this.breath = breath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deviceid=").append(deviceid);
        sb.append(", realtime=").append(realtime);
        sb.append(", heart=").append(heart);
        sb.append(", breath=").append(breath);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}