package com.boat.pension.model;

import java.io.Serializable;

public class Room implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer instid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.instName
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String instname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.wokerID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer wokerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.num
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.buildingName
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String buildingname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.floor
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.size
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.id
     *
     * @return the value of room.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.id
     *
     * @param id the value for room.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.instID
     *
     * @return the value of room.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getInstid() {
        return instid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.instID
     *
     * @param instid the value for room.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setInstid(Integer instid) {
        this.instid = instid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.instName
     *
     * @return the value of room.instName
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getInstname() {
        return instname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.instName
     *
     * @param instname the value for room.instName
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setInstname(String instname) {
        this.instname = instname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.wokerID
     *
     * @return the value of room.wokerID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getWokerid() {
        return wokerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.wokerID
     *
     * @param wokerid the value for room.wokerID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setWokerid(Integer wokerid) {
        this.wokerid = wokerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.num
     *
     * @return the value of room.num
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.num
     *
     * @param num the value for room.num
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.buildingName
     *
     * @return the value of room.buildingName
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getBuildingname() {
        return buildingname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.buildingName
     *
     * @param buildingname the value for room.buildingName
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setBuildingname(String buildingname) {
        this.buildingname = buildingname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.floor
     *
     * @return the value of room.floor
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.floor
     *
     * @param floor the value for room.floor
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.size
     *
     * @return the value of room.size
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.size
     *
     * @param size the value for room.size
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", instid=").append(instid);
        sb.append(", instname=").append(instname);
        sb.append(", wokerid=").append(wokerid);
        sb.append(", num=").append(num);
        sb.append(", buildingname=").append(buildingname);
        sb.append(", floor=").append(floor);
        sb.append(", size=").append(size);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}