package com.boat.pension.model;

import java.io.Serializable;
import java.util.Date;

public class Senior implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senior.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senior.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer instid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senior.pic
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senior.name
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senior.gender
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senior.IDNum
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String idnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senior.tel
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senior.heart
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer heart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senior.breath
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer breath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senior.registerTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Date registertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senior.cont1
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String cont1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senior.cTel1
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String ctel1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senior.cont2
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String cont2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senior.cTel2
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String ctel2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table senior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column senior.id
     *
     * @return the value of senior.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column senior.id
     *
     * @param id the value for senior.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column senior.instID
     *
     * @return the value of senior.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getInstid() {
        return instid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column senior.instID
     *
     * @param instid the value for senior.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setInstid(Integer instid) {
        this.instid = instid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column senior.pic
     *
     * @return the value of senior.pic
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column senior.pic
     *
     * @param pic the value for senior.pic
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column senior.name
     *
     * @return the value of senior.name
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column senior.name
     *
     * @param name the value for senior.name
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column senior.gender
     *
     * @return the value of senior.gender
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column senior.gender
     *
     * @param gender the value for senior.gender
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column senior.IDNum
     *
     * @return the value of senior.IDNum
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getIdnum() {
        return idnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column senior.IDNum
     *
     * @param idnum the value for senior.IDNum
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setIdnum(String idnum) {
        this.idnum = idnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column senior.tel
     *
     * @return the value of senior.tel
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column senior.tel
     *
     * @param tel the value for senior.tel
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column senior.heart
     *
     * @return the value of senior.heart
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getHeart() {
        return heart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column senior.heart
     *
     * @param heart the value for senior.heart
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setHeart(Integer heart) {
        this.heart = heart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column senior.breath
     *
     * @return the value of senior.breath
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getBreath() {
        return breath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column senior.breath
     *
     * @param breath the value for senior.breath
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setBreath(Integer breath) {
        this.breath = breath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column senior.registerTime
     *
     * @return the value of senior.registerTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column senior.registerTime
     *
     * @param registertime the value for senior.registerTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column senior.cont1
     *
     * @return the value of senior.cont1
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getCont1() {
        return cont1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column senior.cont1
     *
     * @param cont1 the value for senior.cont1
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setCont1(String cont1) {
        this.cont1 = cont1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column senior.cTel1
     *
     * @return the value of senior.cTel1
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getCtel1() {
        return ctel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column senior.cTel1
     *
     * @param ctel1 the value for senior.cTel1
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setCtel1(String ctel1) {
        this.ctel1 = ctel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column senior.cont2
     *
     * @return the value of senior.cont2
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getCont2() {
        return cont2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column senior.cont2
     *
     * @param cont2 the value for senior.cont2
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setCont2(String cont2) {
        this.cont2 = cont2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column senior.cTel2
     *
     * @return the value of senior.cTel2
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getCtel2() {
        return ctel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column senior.cTel2
     *
     * @param ctel2 the value for senior.cTel2
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setCtel2(String ctel2) {
        this.ctel2 = ctel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", instid=").append(instid);
        sb.append(", pic=").append(pic);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", idnum=").append(idnum);
        sb.append(", tel=").append(tel);
        sb.append(", heart=").append(heart);
        sb.append(", breath=").append(breath);
        sb.append(", registertime=").append(registertime);
        sb.append(", cont1=").append(cont1);
        sb.append(", ctel1=").append(ctel1);
        sb.append(", cont2=").append(cont2);
        sb.append(", ctel2=").append(ctel2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}