package com.boat.pension.model;

import java.io.Serializable;
import java.util.Date;

public class Usersenior implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersenior.userID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersenior.seniorID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer seniorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersenior.bindTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Date bindtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usersenior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersenior.userID
     *
     * @return the value of usersenior.userID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersenior.userID
     *
     * @param userid the value for usersenior.userID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersenior.seniorID
     *
     * @return the value of usersenior.seniorID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getSeniorid() {
        return seniorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersenior.seniorID
     *
     * @param seniorid the value for usersenior.seniorID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setSeniorid(Integer seniorid) {
        this.seniorid = seniorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersenior.bindTime
     *
     * @return the value of usersenior.bindTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Date getBindtime() {
        return bindtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersenior.bindTime
     *
     * @param bindtime the value for usersenior.bindTime
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setBindtime(Date bindtime) {
        this.bindtime = bindtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersenior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", seniorid=").append(seniorid);
        sb.append(", bindtime=").append(bindtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}