package com.boat.pension.model;

import java.io.Serializable;

public class Wechatuser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.openid
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.tel
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.isWorker
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer isworker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.workerId
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer workerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatuser
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.id
     *
     * @return the value of wechatuser.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.id
     *
     * @param id the value for wechatuser.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.openid
     *
     * @return the value of wechatuser.openid
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.openid
     *
     * @param openid the value for wechatuser.openid
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.tel
     *
     * @return the value of wechatuser.tel
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.tel
     *
     * @param tel the value for wechatuser.tel
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.isWorker
     *
     * @return the value of wechatuser.isWorker
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getIsworker() {
        return isworker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.isWorker
     *
     * @param isworker the value for wechatuser.isWorker
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setIsworker(Integer isworker) {
        this.isworker = isworker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.workerId
     *
     * @return the value of wechatuser.workerId
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getWorkerid() {
        return workerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.workerId
     *
     * @param workerid the value for wechatuser.workerId
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setWorkerid(Integer workerid) {
        this.workerid = workerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", openid=").append(openid);
        sb.append(", tel=").append(tel);
        sb.append(", isworker=").append(isworker);
        sb.append(", workerid=").append(workerid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}