package com.boat.pension.model;

import java.io.Serializable;

public class Worker implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private Integer instid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.num
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.name
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.gender
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.IDNum
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String idnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.tel
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table worker
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.id
     *
     * @return the value of worker.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.id
     *
     * @param id the value for worker.id
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.instID
     *
     * @return the value of worker.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public Integer getInstid() {
        return instid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.instID
     *
     * @param instid the value for worker.instID
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setInstid(Integer instid) {
        this.instid = instid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.num
     *
     * @return the value of worker.num
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.num
     *
     * @param num the value for worker.num
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.name
     *
     * @return the value of worker.name
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.name
     *
     * @param name the value for worker.name
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.gender
     *
     * @return the value of worker.gender
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.gender
     *
     * @param gender the value for worker.gender
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.IDNum
     *
     * @return the value of worker.IDNum
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getIdnum() {
        return idnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.IDNum
     *
     * @param idnum the value for worker.IDNum
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setIdnum(String idnum) {
        this.idnum = idnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.tel
     *
     * @return the value of worker.tel
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.tel
     *
     * @param tel the value for worker.tel
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", instid=").append(instid);
        sb.append(", num=").append(num);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", idnum=").append(idnum);
        sb.append(", tel=").append(tel);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}