package com.boat.pension.mapper;

import com.boat.pension.model.Monitorlog;
import com.boat.pension.model.MonitorlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MonitorlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorlog
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    long countByExample(MonitorlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorlog
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int deleteByExample(MonitorlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorlog
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorlog
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int insert(Monitorlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorlog
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int insertSelective(Monitorlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorlog
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    List<Monitorlog> selectByExample(MonitorlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorlog
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    Monitorlog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorlog
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByExampleSelective(@Param("record") Monitorlog record, @Param("example") MonitorlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorlog
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByExample(@Param("record") Monitorlog record, @Param("example") MonitorlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorlog
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByPrimaryKeySelective(Monitorlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorlog
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByPrimaryKey(Monitorlog record);
}