package com.boat.pension.mapper;

import com.boat.pension.model.Senior;
import com.boat.pension.model.SeniorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeniorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    long countByExample(SeniorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int deleteByExample(SeniorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int insert(Senior record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int insertSelective(Senior record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    List<Senior> selectByExample(SeniorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    Senior selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByExampleSelective(@Param("record") Senior record, @Param("example") SeniorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByExample(@Param("record") Senior record, @Param("example") SeniorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByPrimaryKeySelective(Senior record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByPrimaryKey(Senior record);
}