package com.boat.pension.mapper;

import com.boat.pension.model.Usersenior;
import com.boat.pension.model.UserseniorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserseniorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersenior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    long countByExample(UserseniorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersenior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int deleteByExample(UserseniorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersenior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int deleteByPrimaryKey(@Param("userid") Integer userid, @Param("seniorid") Integer seniorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersenior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int insert(Usersenior record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersenior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int insertSelective(Usersenior record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersenior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    List<Usersenior> selectByExample(UserseniorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersenior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    Usersenior selectByPrimaryKey(@Param("userid") Integer userid, @Param("seniorid") Integer seniorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersenior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByExampleSelective(@Param("record") Usersenior record, @Param("example") UserseniorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersenior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByExample(@Param("record") Usersenior record, @Param("example") UserseniorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersenior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByPrimaryKeySelective(Usersenior record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersenior
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByPrimaryKey(Usersenior record);
}