package com.boat.pension.mapper;

import com.boat.pension.model.Wechatuser;
import com.boat.pension.model.WechatuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    long countByExample(WechatuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int deleteByExample(WechatuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int insert(Wechatuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int insertSelective(Wechatuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    List<Wechatuser> selectByExample(WechatuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    Wechatuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByExampleSelective(@Param("record") Wechatuser record, @Param("example") WechatuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByExample(@Param("record") Wechatuser record, @Param("example") WechatuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByPrimaryKeySelective(Wechatuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbg.generated Mon Jul 25 21:36:27 CST 2022
     */
    int updateByPrimaryKey(Wechatuser record);
}